server:
  port: 8080
  servlet:
    context-path: /banking

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/prj_banking"
    username: root
    password: nam01665478954
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jwt:
    SIGNER_KEY: rw+RZk7bM6N5TRv75gsYuGg3tkU7WuRAvYNscwpLD6Mq91wnIzkwI0FBaog/wsoY
    VALID_DURATION: 20
    REFRESHABLE_DURATION: 100  #in seconds

