server:
  port: 8080
  servlet:
    context-path: /banking

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/prj_banking"
    username: root
    password: nam01665478954
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "rw+RZk7bM6N5TRv75gsYuGg3tkU7WuRAvYNscwpLD6Mq91wnIzkwI0FBaog/wsoY"
  VALID-DURATION: 300         #in seconds
  REFRESHABLE-DURATION: 3000  #in seconds

